TurtleMail = TurtleMail or {}

local L= {}
TurtleMail.L = L
setmetatable( L, { __index = function( _, key) return key end } );

L[ "collected" ] = nil
L[ "1st mail" ] = nil
L[ "each mail" ] = nil
L[ "Money received" ] = nil
L[ "All mails" ] = nil
L[ "This mail was returned to you." ] = nil
L[ "This mail was sent by an auctionhouse." ] = nil
L[ "Log" ] = nil
L[ "Received" ] = nil
L[ "Sent" ] = nil
L[ "Auction House" ] = nil
L[ "Returned" ] = nil
L[ "Help" ] = nil
L[ "Toggle logging on/off" ] = nil
L[ "Clear sent log" ] = nil
L[ "Clear received log" ] = nil
L[ "Logging is enabled." ] = nil
L[ "Logging is disabled." ] = nil
L[ "Sent log cleared." ] = nil
L[ "Received log cleared." ] = nil
L[ "AH" ] = "Auction House"
L[ "COD" ] = "C.O.D."
L[ "Money" ] = "Money Attached"
L[ "Players" ] = nil
L[ "All players" ] = nil
L[ "Clear..." ] = nil
L[ "Clear all mail logs" ] = nil
L[ "Delete logs older than X days (default: 30)" ] = nil
L[ "Prune older than 7 days" ] = nil
L[ "Prune older than 14 days" ] = nil
L[ "Prune older than 30 days" ] = nil
L[ "Prune older than 60 days" ] = nil
L[ "Clear current log" ] = nil
L[ "Clear ALL logs" ] = nil
L[ "date_format" ] = "%d.%m.%Y"
L[ "time_format" ] = "%H:%M"